sudo: false

language: perl

git:
  depth: 3
  
perl:
  - 5.20
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10

# disable cpanm

before_install: true

install: true

before_script:
  - perlbrew use $PERLVERS
  - ./bootstrap

script:
  - ./configure
  - make
  - make dist
  - mkdir ~/src
  - cp acmefetch*.tar.gz ~/src
  - cd ~/src
  - tar xvf acme*gz
  - cd acme*/
  - ./configure --prefix=$HOME/acmefetch
  - make
  - make install
  - cd $HOME/acmefetch/bin  
  - ./acmefetch --version

