sudo: false

language: c

git:
  depth: 3
  
env:
  - PERLVERS=5.20
  - PERLVERS=5.18
  - PERLVERS=5.16
  - PERLVERS=5.14
  - PERLVERS=5.12
  - PERLVERS=5.10

before_script:
  - perlbrew install perl-$PERLVERS
  - ./bootstrap

script:
  - ./configure
  - make
  - make dist
  - mkdir ~/src
  - cp acmefetch*.tar.gz ~/src
  - cd ~/src
  - tar xvf acme*gz
  - cd acme*/
  - ./configure --prefix=$HOME/acmefetch
  - make
  - make install
  - cd $HOME/acmefetch/bin  
  - ./acmefetch --version

